apiVersion: v1
kind: Pod
metadata:
  name: e2e-api-pod
  labels:
    name: "e2e-api-pod"
spec:
  containers:
    - name: main
      image: quay.io/numaio/numaflow-go/e2eapi:latest
      imagePullPolicy: IfNotPresent
