name: CI
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
jobs:
  aws-sqs-source-go:
    name: aws-sqs-source-go
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOPATH: /home/runner/go
    steps:
      - name: "Step 1: Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: "Step 2: Run prerequisite steps"
        run: |
          echo "IMAGE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0

      - name: "Step 3: Setup Golang"
        uses: actions/setup-go@v4.0.0
        with:
          go-version: '1.21'

      - name: "Step 4: Restore Go build cache"
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}

      - name: "Step 5: Run Lint"
        run: make lint

      - name: Get IP
        id: getip
        run: echo "::set-output name=ip::$(hostname -I | awk '{print $1}')"

      - name: Print IP
        run: |
          echo "IP Address: ${{ steps.getip.outputs.ip }}"    

      - name: "Step 6: Run Unit Tests"
        run: make test

      - name: "Step 7: Run e2e  Tests"
        run: make test-e2e



      - name: "Step 8: Build and create docker image"
        run: make image
        env:
          TAG: ${{ env.IMAGE_TAG }}

      - name: "Step 7: Docker Login"
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}

      - name: "Step 8: Build docker image"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker push "quay.io/numaio/numaflow-go/aws-sqs-source-go:${{env.IMAGE_TAG}}"